services:
    netgen_open_weather_map.controller.weather:
        class: Netgen\Bundle\OpenWeatherMapBundle\Controller\WeatherController
        arguments:
            - '@netgen_open_weather_map.weather'

    netgen_open_weather_map.controller.ultraviolet_index:
        class: Netgen\Bundle\OpenWeatherMapBundle\Controller\UltravioletIndexController
        arguments:
            - '@netgen_open_weather_map.ultraviolet_index'

    netgen_open_weather_map.controller.hour_forecast:
        class: Netgen\Bundle\OpenWeatherMapBundle\Controller\HourForecastController
        arguments:
            - '@netgen_open_weather_map.hour_forecast'

    netgen_open_weather_map.controller.daily_forecast:
        class: Netgen\Bundle\OpenWeatherMapBundle\Controller\DailyForecastController
        arguments:
            - '@netgen_open_weather_map.daily_forecast'

    netgen_open_weather_map.controller.air_pollution:
        class: Netgen\Bundle\OpenWeatherMapBundle\Controller\AirPollutionController
        arguments:
            - '@netgen_open_weather_map.air_pollution'
