imports:
    - { resource: controllers.yml }
    - { resource: weather.yml }
    - { resource: factories.yml }

parameters:
    netgen_open_weather_map.http.client.class: Netgen\Bundle\OpenWeatherMapBundle\Http\HttpClient
    netgen_open_weather_map.factory.cache.class: Netgen\Bundle\OpenWeatherMapBundle\Factory\CacheHandlerFactory
    netgen_open_weather_map.cache_handler.class: Netgen\Bundle\OpenWeatherMapBundle\Cache\HandlerInterface

services:
    netgen_open_weather_map.factory.cache:
        class: '%netgen_open_weather_map.factory.cache.class%'
        arguments:
            - '$cache_settings;netgen_open_weather_map$'
            - '@service_container'

    netgen_open_weather_map.cache_handler:
        class: '%netgen_open_weather_map.cache_handler.class%'
        factory: ['@netgen_open_weather_map.factory.cache', getCacheHandler]

    netgen_open_weather_map.http.client:
        class: '%netgen_open_weather_map.http.client.class%'
