services:
    netgen_open_weather_map.weather:
        class: Marek\OpenWeatherMap\Core\Weather\Weather
        factory: 'netgen_open_weather_map.factory.weather:createWeatherService'

    netgen_open_weather_map.air_pollution:
        class: Marek\OpenWeatherMap\Core\Weather\AirPollution
        factory: 'netgen_open_weather_map.factory.weather:createAirPollutionService'

    netgen_open_weather_map.daily_forecast:
        class: Marek\OpenWeatherMap\Core\Weather\DailyForecast
        factory: 'netgen_open_weather_map.factory.weather:createDailyForecastService'

    netgen_open_weather_map.hour_forecast:
        class: Marek\OpenWeatherMap\Core\Weather\HourForecast
        factory: 'netgen_open_weather_map.factory.weather:createHourForecastService'

    netgen_open_weather_map.ultraviolet_index:
        class: Marek\OpenWeatherMap\Core\Weather\UltravioletIndex
        factory: 'netgen_open_weather_map.factory.weather:createUltravioletIndexService'

    netgen_open_weather_map.weather_services:
        class: Marek\OpenWeatherMap\Core\WeatherServices
        arguments:
            - '@netgen_open_weather_map.weather'
            - '@netgen_open_weather_map.hour_forecast'
            - '@netgen_open_weather_map.daily_forecast'
            - '@netgen_open_weather_map.ultraviolet_index'
            - '@netgen_open_weather_map.air_pollution'
